version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_card_db
    ports:
      - "5432:5432"
    networks:
      - bank_card_network

  app:
    image: openjdk:11-jdk
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - bank_card_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_card_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

networks:
  bank_card_network:
    driver: bridge
